import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "@/app/globals.css";
import NavBar from "@/components/web/loginNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Login</title>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded"
        />
        <link
          href="https://db.onlinewebfonts.com/c/4a24899e94d8236f671c1090cd9e068c?family=Canela-Regular"
          rel="stylesheet"
          type="text/css"
        />
        <style>{`
          h1 {
     
         font-family: 'Canela-Regular', serif;
          }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212]`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="dark">
          {/* NavBar  */}
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
