import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavigationBar from "@/components/web/chat_sidebar";
import FooterBar from "@/components/web/footer";
import { ThemeProvider } from "next-themes";
import "@xyflow/react/dist/style.css";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row`}
    >
      <ThemeProvider attribute="class" enableSystem defaultTheme="dark">
        {children}
        {modal}
      </ThemeProvider>
    </body>
  );
}
